language: python
python:
  - "2.7"
env:
  - DJANGO=1.6 DB=sqlite
  - DJANGO=1.7 DB=sqlite
  - DJANGO=1.8 DB=sqlite
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls coverage django-discover-runner
script:
  - coverage run --rcfile=.coveragerc setup.py test
after_success:
  - coveralls